server:
  port: 8080
spring:
  application:
    name: plant_lab
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/plantlab?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
#  task:
#    scheduling:
#      fixedRate: 60000
mybatis-plus:
    configuration:
#      在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
      map-underscore-to-camel-case: true
#      日志功能，查看MyBatis-Plus自动生成的sql语句
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-aliases-package: hc.mapper
    global-config:
      db-config:
        logic-delete-field: isDeleted
        logic-not-delete-value: 0
        logic-delete-value: 1
file:
  video:
    url: C:\Users\HOVER\Videos\开发
    playUrl: http://192.168.2.54
  userFile:
    url: C:\Projects\Logs\plantFile\userFile
  gptFile:
    url: C:\Projects\Logs\plantFile\gptFile

